//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gazi_Salon_Takip.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    [FluentValidation.Attributes.Validator(typeof(ProgramValidator))]
    public partial class Program
    {
        public int ID { get; set; }
        [Display(Name = "Salon")]
        public Nullable<int> SalonID { get; set; }

        [Display(Name = "Tarih")]
        [DisplayFormat(DataFormatString = "{0:dd.MM.yyyy}")]
        public Nullable<System.DateTime> Program_Tarih { get; set; }
        [Display(Name = "Başlangıç")]
        [DisplayFormat(DataFormatString = "{0:H.mm}")]
        public Nullable<System.DateTime> Program_Baslangic { get; set; }
        [Display(Name = "Bitiş")]
        [DisplayFormat(DataFormatString = "{0:H.mm}")]
        public Nullable<System.DateTime> Program_Bitis { get; set; }
        [Display(Name = "Ad")]
        public string Program_Adı { get; set; }
        [Display(Name = "Sahip")]
        public string Program_Sahip { get; set; }
        [Display(Name = "Açıklama")]
        public string Program_Aciklama { get; set; }
        public Nullable<bool> Is_Delete { get; set; }
    
        public virtual Salon Salon { get; set; }
    }
}
