//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gazi_Salon_Takip.Models.EntityFramework
{
    using Gazi_Salon_Takip.Models.ValidationRules.FluentValidation;
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    [FluentValidation.Attributes.Validator(typeof(SalonValidator))]
    public partial class Salon
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Salon()
        {
            this.Programs = new HashSet<Program>();
        }
    
        public int ID { get; set; }
        [Display(Name = "Salon")]
        public string Salon_Adi { get; set; }
        [Display(Name = "Adres")]
        public string Salon_Adresi { get; set; }
        [Display(Name = "Salon Bilgisi")]
        public string SalonBilgisi { get; set; }
        [Display(Name = "Ýletiþim")]
        public string Salon_Iletisim { get; set; }
        public Nullable<bool> Is_Delete { get; set; }
        public Nullable<int> SalonGoruntulenme { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Program> Programs { get; set; }
    }
}
