//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Gazi_Salon_Takip.Models.EntityFramework
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Uye
    {
        public int uyeID { get; set; }
        [Display(Name = "Ad Soyad")]
        public string KullaniciAdSoyad { get; set; }
        [Display(Name = "Kullanýcý Adý")]
        public string KullaniciAd { get; set; }
        [Display(Name = "Email")]
        public string KullaniciEmail { get; set; }
        [Display(Name = "Þifre")]
        public string KullaniciSifre { get; set; }
        public Nullable<int> YetkiID { get; set; }
    
        public virtual Yetki Yetki { get; set; }
    }
}
